### ISSUE TITLE
How to save and load face feature database to disk in python?

### ISSUE THREAD

**Issue by nauyeskhan-monosoft** [HyperInspire/InspireFace#111]
I am using InspireFace’s FeatureHub in Python to handle face recognition features, and I would like to save the extracted features for millions of images in a persistent database file. My goal is to avoid reprocessing and reinserting each feature on every run.

Currently, I’ve configured FeatureHub as follows:

```
feature_hub_config = ifac.FeatureHubConfiguration(
    feature_block_num=20,
    enable_use_db=True,
    db_path="face_features.db",
    search_threshold=-1,
    search_mode=ifac.HF_SEARCH_MODE_EXHAUSTIVE,
)
ret = ifac.feature_hub_enable(feature_hub_config)
assert ret, "Failed to enable FeatureHub."


for idx, image_name in tqdm(enumerate(os.listdir(origin_database_path))):
    image_path = os.path.join(origin_database_path, image_name)
    if image_path.endswith((".jpg", ".jpeg", ".png")):
        image = cv2.imread(image_path)
        assert image is not None, f"Failed to load image {image_path}"
        faces = session.face_detection(image)
        if faces:
            face = faces[0]  # Use the first detected face
            feature = session.face_feature_extract(image, face)
            identity = ifac.FaceIdentity(feature, custom_id=idx, tag=image_name)
            ret = ifac.feature_hub_face_insert(identity)
            assert ret, f"Failed to insert face for {image_name}"
```

Despite setting `enable_use_db=True` and specifying `db_path`, I don’t see any database file saved at the specified location. Is there an option or additional method to save the FeatureHub to disk, so that it can be loaded directly in a new session without re-insertion? If so, could you provide guidance on how to do this in Python?

**Comment by tunmx** [comment]
Thanks for your feedback. Theoretically, if you specify db_path, it should be stored. If not, there may be some problems, I will test the latest version later and give you feedback.

**Comment by tunmx** [comment]
Sorry, I haven't updated it yet, maybe it needs to be on the weekend.

**Comment by tunmx** [comment]
Hi, I've fixed this issue and added Python test cases. It occurred in the Python native interface, so you just need to pull the code - no need to recompile the dynamic library.  #112 

`import os
import cv2
import inspireface as ifac
from inspireface.param import *
import numpy as np
import os

def case_feature_hub():
    db_path = "test.db"
    if os.path.exists(db_path):
        os.remove(db_path)
    # Configure the feature management system.
    feature_hub_config = ifac.FeatureHubConfiguration(
        feature_block_num=10,
        enable_use_db=True,
        db_path=db_path,
        search_threshold=0.48,
        search_mode=HF_SEARCH_MODE_EAGER,
    )
    ret = ifac.feature_hub_enable(feature_hub_config)
    assert ret, "Failed to enable FeatureHub."
    print(ifac.feature_hub_get_face_count())
    for i in range(10):
        feature = ifac.FaceIdentity(np.random.rand(512), i, "test")
        ifac.feature_hub_face_insert(feature)
    print(ifac.feature_hub_get_face_count())

    assert os.path.exists(db_path), "FeatureHub database file not found."


if __name__ == "__main__":
    case_feature_hub()
`

**Comment by nauyeskhan-monosoft** [comment]
Hello @tunmx !

The problem with db file NOT saving came back with the latest update. 
This time I have installed InspireFace with `pip`, no other manipulations were done. 
After inserting all features, no .db file is being saved.

**Comment by tunmx** [comment]
Hi @nauyeskhan-monosoft .This was a serious bug, but I've fixed it now. Please try the latest version(1.1.11).

**Comment by player1008611** [comment]
How to implement it on the rv1106 platform? Part of my code is as follows, but no .db file was generated after running. Is there an issue with my settings?

    HFFeatureHubConfiguration featureHubConfiguration;
    featureHubConfiguration.primaryKeyMode = HF_PK_AUTO_INCREMENT; 
    featureHubConfiguration.enablePersistence = 1;                 
    featureHubConfiguration.persistenceDbPath = "/root/feature.db";      
    featureHubConfiguration.searchMode = HF_SEARCH_MODE_EAGER;     
    featureHubConfiguration.searchThreshold = 0.48f;             

    ret = HFFeatureHubDataEnable(featureHubConfiguration);
    if (ret != HSUCCEED)
    {
        printf("Enable FeatureHub failed: %d\n", ret);
        return ret;
    }

    
    HOption option = HF_ENABLE_FACE_RECOGNITION | HF_ENABLE_LIVENESS;
    ret = HFCreateInspireFaceSessionOptional(option, HF_DETECT_MODE_LIGHT_TRACK, 1, 160, -1, &g_face_session);
    if (ret != HSUCCEED)
    {
        printf("Create session error: %d\n", ret);
        return ret;
    }
    HFSessionSetTrackPreviewSize(g_face_session, 386);
    HFSessionSetFilterMinimumFacePixelSize(g_face_session, 4);
    HInt32 face_count = 0;
    HFFeatureHubGetFaceCount(&face_count);
    if (face_count == 0)
    {
        LoadReferenceFace(); //I insert some features from picture to Featurehub in this function
    }
    else
    {
        printf(" %d features loaded from database\n", face_count);
    }
    HFFeatureHubViewDBTable();

**Comment by tunmx** [comment]
Your Settings seem to be correct. Are there any other errors? Or is it running successfully and still unable to create a db file?

**Comment by player1008611** [comment]
I compiled the latest version, but it still doesn't work properly. HFFeatureHubViewDBTable() can correctly return the features currently in the database, but I don't see any .db files being created.

LoadReferenceFace
face feature name: ./faces/3.png
The device support dot:0, support fp16:0, support i8mm: 0
rga_api version 1.10.1_[0]
Feature insertion into FeatureHub id: 1, 3
face feature name: ./faces/2.png
Feature insertion into FeatureHub id: 2, 2
face feature name: ./faces/1.png
No face was detected: 1.png, 0
Inserted data: 2
LoadReferenceFace finished, 2 faces loaded.
=== Table Content ===
ID | Vector (first 5 elements)
------------------------
1 | -0.009388, -0.032186, 0.128746, -0.044256, 0.093877...
2 | -0.010607, 0.010607, -0.031821, -0.021214, -0.010607...

**Comment by tunmx** [comment]
ok, I will find an rv1106 development board to test it later

**Comment by tunmx** [comment]
Hi @player1008611, To facilitate verification, I extracted the DB persistence mode portion from the unit test code and tested it using a simple sample. You can check out the example here: [sample_feature_hub_persistence.c]
(https://github.com/HyperInspire/InspireFace/blob/master/cpp/sample/api/sample_feature_hub_persistence.c):
```c
HFFeatureHubConfiguration featureHubConfiguration;
  featureHubConfiguration.primaryKeyMode = HF_PK_AUTO_INCREMENT; 
  featureHubConfiguration.enablePersistence = 1;                 
  featureHubConfiguration.persistenceDbPath = DBFilePath;      
  featureHubConfiguration.searchMode = HF_SEARCH_MODE_EAGER;     
  featureHubConfiguration.searchThreshold = 0.48f;             

  ret = HFFeatureHubDataEnable(featureHubConfiguration);
  if (ret != HSUCCEED)
  {
      HFLogPrint(HF_LOG_ERROR, "Enable FeatureHub failed: %d\n", ret);
      return ret;
  }
  if (access(DBFilePath, F_OK) != 0) {
      HFLogPrint(HF_LOG_ERROR, "DB file not found: %s", DBFilePath);
      return -1;
  }
  HFLogPrint(HF_LOG_INFO, "DB file found: %s", DBFilePath);
```

I also tested it on the RV1106 development board and confirmed that the DB file was successfully created.

![Image](https://github.com/user-attachments/assets/2d30470f-33e5-4f67-a414-5d7a57113d6c)

So, I think the problem might be with storage permissions on the device. Maybe check if the folder you're saving the DB file to has any special restrictions, or if the program has permission to write there.

**Comment by player1008611** [comment]
After compiling the latest version of libInspireFace.so, I did not copy it to the lib directory on the development board, which was clearly the root cause of the problem. Everything is working properly now.

**Comment by tunmx** [comment]
resolved
